export const MOCK_EXPERTS = [
  {
    id: "1",
    name: "Raoul Pal",
    handle: "raoulpal",
    title: "Macro Strategist & CEO of Real Vision",
    bio: "Former Goldman Sachs hedge fund manager. Expert in global macro, crypto, and financial markets.",
    avatar: "/raoul-pal-macro.jpg",
    verified: true,
    available: true,
    contentCount: 247,
    category: "Macro & Markets",
  },
  {
    id: "2",
    name: "Cathie Wood",
    handle: "cathiewood",
    title: "CEO & CIO of ARK Invest",
    bio: "Innovation investor focused on disruptive technologies and transformative companies.",
    avatar: "/cathie-wood-ark.jpg",
    verified: true,
    available: true,
    contentCount: 189,
    category: "Innovation & Tech",
  },
  {
    id: "3",
    name: "Michael Saylor",
    handle: "saylor",
    title: "Executive Chairman of MicroStrategy",
    bio: "Bitcoin advocate and corporate treasury strategist. Leading voice on Bitcoin adoption.",
    avatar: "/michael-saylor.jpg",
    verified: true,
    available: false,
    contentCount: 312,
    category: "Bitcoin & Crypto",
  },
  {
    id: "4",
    name: "Lyn Alden",
    handle: "lynalden",
    title: "Founder of Lyn Alden Investment Strategy",
    bio: "Investment strategist covering macro, value investing, and technology trends.",
    avatar: "/lyn-alden.jpg",
    verified: true,
    available: true,
    contentCount: 156,
    category: "Macro & Markets",
  },
]

export const MOCK_VIDEO_RESOURCES = [
  {
    id: "v1",
    citationNumber: 1,
    videoTitle: "System Design Interview Masterclass - From SDE1 to SDE2",
    channelName: "Tech Lead",
    publishDate: "2024-01-10",
    timestamp: "0:45",
    timestampSeconds: 45,
    thumbnailUrl: "https://img.youtube.com/vi/F1bfo7bKfMI/hqdefault.jpg",
    youtubeUrl: "https://youtube.com/watch?v=F1bfo7bKfMI",
    viewCount: 450000,
  },
  {
    id: "v2",
    citationNumber: 2,
    videoTitle: "Building Production-Grade Systems - Database Choices",
    channelName: "ByteByteGo",
    publishDate: "2024-01-08",
    timestamp: "12:30",
    timestampSeconds: 750,
    thumbnailUrl: "https://img.youtube.com/vi/ukLkqLPYAQo/hqdefault.jpg",
    youtubeUrl: "https://youtube.com/watch?v=ukLkqLPYAQo",
    viewCount: 380000,
  },
  {
    id: "v3",
    citationNumber: 3,
    videoTitle: "Coding Interview Patterns - Dynamic Programming & Graphs",
    channelName: "NeetCode",
    publishDate: "2024-01-12",
    timestamp: "8:15",
    timestampSeconds: 495,
    thumbnailUrl: "https://img.youtube.com/vi/Xmi0F51BN2Q/hqdefault.jpg",
    youtubeUrl: "https://youtube.com/watch?v=Xmi0F51BN2Q",
    viewCount: 520000,
  },
  {
    id: "v4",
    citationNumber: 4,
    videoTitle: "Microservices Architecture: API Gateway & Service Discovery",
    channelName: "Hussein Nasser",
    publishDate: "2024-01-05",
    timestamp: "15:22",
    timestampSeconds: 922,
    thumbnailUrl: "https://img.youtube.com/vi/x-RfIXn0S1k/hqdefault.jpg",
    youtubeUrl: "https://youtube.com/watch?v=x-RfIXn0S1k",
    viewCount: 290000,
  },
  {
    id: "v5",
    citationNumber: 5,
    videoTitle: "Becoming a Better Engineer - Code Quality & Architecture",
    channelName: "Coding Blocks",
    publishDate: "2024-01-03",
    timestamp: "22:45",
    timestampSeconds: 1365,
    thumbnailUrl: "https://img.youtube.com/vi/L1IiRaKhwvM/hqdefault.jpg",
    youtubeUrl: "https://youtube.com/watch?v=L1IiRaKhwvM",
    viewCount: 340000,
  },
  {
    id: "v6",
    citationNumber: 6,
    videoTitle: "Distributed Systems Fundamentals - Consistency & Availability",
    channelName: "MIT OpenCourseWare",
    publishDate: "2023-12-28",
    timestamp: "35:18",
    timestampSeconds: 2118,
    thumbnailUrl: "https://img.youtube.com/vi/3GZiXc7zcOo/hqdefault.jpg",
    youtubeUrl: "https://youtube.com/watch?v=3GZiXc7zcOo",
    viewCount: 420000,
  },
]

export const MOCK_ARTICLE_SOURCES = [
  {
    id: "a1",
    citationNumber: 1,
    title: "Building Strong Foundations in Computer Science",
    author: "Dr. Sarah Chen",
    publishDate: "2024-01-10",
    source: "Medium",
    url: "https://medium.com/tech-insights/cs-foundations",
    summary: "A comprehensive guide to essential computer science concepts",
  },
  {
    id: "a2",
    citationNumber: 2,
    title: "Data Structures Every Developer Should Know",
    author: "Alex Rodriguez",
    publishDate: "2024-01-05",
    source: "Dev.to",
    url: "https://dev.to/data-structures-guide",
    summary: "Essential data structures explained with practical examples",
  },
  {
    id: "a3",
    citationNumber: 3,
    title: "Mastering Algorithms: Your Learning Path",
    author: "Jamie Kim",
    publishDate: "2024-01-08",
    source: "LinkedIn",
    url: "https://linkedin.com/articles/algorithm-mastery",
    summary: "Step-by-step guide to learning algorithms effectively",
  },
  {
    id: "a4",
    citationNumber: 4,
    title: "System Design Patterns in Practice",
    author: "Marcus Johnson",
    publishDate: "2024-01-12",
    source: "Dev.to",
    url: "https://dev.to/system-design-patterns",
    summary: "Real-world system design patterns and implementations",
  },
  {
    id: "a5",
    citationNumber: 5,
    title: "Database Selection Guide for Modern Apps",
    author: "Emma Watson",
    publishDate: "2024-01-09",
    source: "Medium",
    url: "https://medium.com/database-guide",
    summary: "Comprehensive guide to choosing the right database",
  },
  {
    id: "a6",
    citationNumber: 6,
    title: "Continuous Learning in Tech Industry",
    author: "David Lee",
    publishDate: "2024-01-15",
    source: "LinkedIn",
    url: "https://linkedin.com/articles/continuous-learning",
    summary: "Strategies for staying up-to-date with technology trends",
  },
  {
    id: "a7",
    citationNumber: 7,
    title: "Career Growth: From Individual Contributor to Leader",
    author: "Rachel Martinez",
    publishDate: "2024-01-14",
    source: "Dev.to",
    url: "https://dev.to/career-growth-guide",
    summary: "Guide to professional development and career advancement",
  },
]

export const MOCK_SUGGESTED_QUESTIONS = [
  {
    id: "1",
    question: "@RaoulPal What's your outlook on Bitcoin for the next 12 months?",
    category: "Bitcoin & Crypto",
  },
  {
    id: "2",
    question: "@Mag7CEOs When will AGI become reality?",
    category: "Innovation & Tech",
  },
  {
    id: "3",
    question: "What are the biggest risks facing global markets right now?",
    category: "Macro & Markets",
  },
  {
    id: "4",
    question: "Which innovation trends are most underappreciated?",
    category: "Innovation & Tech",
  },
  {
    id: "5",
    question: "How should I diversify my portfolio during this cycle?",
    category: "Macro & Markets",
  },
]

